export enum EPublicationType {
  Article = 'Article',
  BookChapter = 'Book Chapter',
  BookReview = 'Book Review',
  Essay = 'Essay',
}

export enum EResearcherNames {
  Ngozika_Obi_Ani = 'Ngozika Anthonia Obi-Ani',
  Mathias_Isiani = 'Mathias Chukwudi Isiani',
  Paul_Obi_Ani = 'Paul Obi-Ani',
  Odinaka_Eze = 'Odinaka Kingsley Eze',
  Chinenye_Anikwenze = 'Chinenye Anikwenze',
  Lovelyn_Isiani = 'Lovelyn Isiani',
  Sochima_Okafor = 'Sochima Okafor',
  Juliet_Isiani = 'Juliet Isiani',
  Alexander_Isiani = 'Alexander Isiani',
  Obinna_Ezeaku = 'Obinna Dominic Ezeaku',
  Ogechi_Ikem = 'Ogechi Akure Ikem',
  Ngozi_Ojiakor = 'Ngozi Ojiakor',
  Stanley_Onyemechalu = 'Stanley Jachike Onyemechalu',
  Somtochukwu_Osinem = 'Somtochukwu C. Osinem',
  Sopuluchukwu_Dimelu = 'Sopuluchukwu Amarachukwu Dimelu',
  Chikelue_Akabuike = 'Chikelue Chris Akabuike',
  Samuel_Adu_Gyamfi = 'Samuel Adu-Gyamfi',
  Janefrances_Onu = 'Janefrances Onu',
  Chukwudi_Chidume = ' Chukwudi Godwin Chidume',
  Stella_Okoye_Ugwu = 'Stella Okoye-Ugwu',
  Uche_Okonkwo = 'Uche Uwaezuoke Okonkwo',
  Cindy_Ezeugwu = 'Cindy Anene Ezeugwu',
  Chijioke_Onah = 'Chijioke Kizito Onah',
  Nnaemeka_Enemchukwu = 'Nnaemeka Enemchukwu',
  Abel_Ugwu = 'Abel Ugwu',
}

export enum EPublisherNames {
  AfricanStudiesReviews = 'African Studies Review',
  Cities = 'Cities',
  KujengaAmani = 'Kujenga Amani',
  CogentArtsAndHumanities = 'Cogent Arts & Humanities',
  NsukkaJournalOfTheHumanities = 'Nsukka Journal of the Humanities',
  JournalOfCulturalHeritageManagementandSustainableDevelopment = 'Journal of Cultural Heritage Management and Sustainable Development',
  SouthAsianJournalOfSocialSciencesAndHumanities = 'South Asian Journal of Social Sciences and Humanities',
  JournalOfOostColonialWriting = 'Journal of Postcolonial Writing',
  CambridgeJournalOfPostcolonialLiteraryInquiry = 'Cambridge Journal of Postcolonial Literary Inquiry',
  JournalOfTheInternationalAfricanInstitute = 'Journal of the International African Institute',
  OpenJournalOfSocialSciences = 'Open Journal Of Social Sciences',
  RoutledgeHandbookOfContemporaryAfricanWomen = 'Routledge Handbook of Contemporary African Women',
}